### ISSUE TITLE
go get github.com/shelld3v/aquatone installs only v 1.9.0 instead of the 2.0

### ISSUE THREAD

**Issue by wellenc-lex** [shelld3v/aquatone#10]
need to update the go repo version

**Comment by wellencamass** [comment]
Its still like that, you could verify it by usrelf. 

go get github.com/shelld3v/aquatone downloads 1.9.0 version without the latest fix for nmap parsing
<img width="431" alt="изображение" src="https://user-images.githubusercontent.com/77920409/152784838-6f306d71-8220-4496-be3a-b59592c952bc.png">

**Comment by shelld3v** [comment]
I see, I haven't made a new release yet for the fix, I will do it soon

**Comment by shelld3v** [comment]
It's fixed now, some weird issues but I was able to fix it, now it's v1.9.1 instead of v2.0.0
