### ISSUE TITLE
nmap parser ignores many ports

### ISSUE THREAD

**Issue by wellencamass** [shelld3v/aquatone#12]
Hello, shell

I've got some questions and i cant find out why thats done that way

When aquatone parses nmap xml it uses https://github.com/shelld3v/aquatone/blob/master/parsers/nmap.go

In this file there is this function

func (p *NmapParser) isHTTPPort(port int) bool {
	for _, p := range core.XLargePortList {
		if p == port {
			return true
		}
	}
	return false
}

It checks if port in xml is in XLargePortList and if it is there then it adds it to the screenshot queue.

Why this function even exists? Whats the problem for aquatone to ask for unusual port?

Why  XLargePortList https://github.com/shelld3v/aquatone/blob/master/core/ports.go has no ports like 10000,10250, etc?

As i see aquatone just drops a lot of juicy information on these unusual ports (kubernetes dashboards, webmin panels, etc)

Cant we just get rid of this function and ask every port in the xml? If its non-http just catch an error and move on?

Regards, wellenc

**Comment by shelld3v** [comment]
This is actually just a fork of https://github.com/michenriksen/aquatone, with many improvements, new features, so I can answer your questions, but yeah I think you are right, I will change that, thank you
