### ISSUE TITLE
install aquatone error

### ISSUE THREAD

**Issue by DonatoReis** [shelld3v/aquatone#15]
Hi @shelld3v , I'm having trouble installing from GO.

with the update go get to go install, I tried but I get this message in the image below.

<a href="https://ibb.co/bsqkRdL"><img src="https://i.ibb.co/Lxb3hp6/Sem-t-tulo1.png" alt="Sem-t-tulo1" border="0"></a>
<a href="https://ibb.co/R33MDBT"><img src="https://i.ibb.co/rxxLwc2/Sem-t-tulo2.png" alt="Sem-t-tulo2" border="0"></a>

**Comment by bru73f0rc3** [comment]
@DonatoReis 
I don't have much experience with go packages and modules, but this works for me:
go mod init github.com/shelld3v/aquatone
go env -w GO111MODULE=off
go get github.com/shelld3v/aquatone
I'm not positive the mod init is required, I honestly didn't look too deep into it,  I just needed it working now.

**Comment by DonatoReis** [comment]
There's still an error. @shelld3v  needs to fix the repository and update to install with go install, because golang no longer accepts go get

**Comment by shelld3v** [comment]
@DonatoReis Is there any other update required besides a documentation update?

**Comment by DonatoReis** [comment]
> @DonatoReis Is there any other update required besides a documentation update?

@shelld3v only the way to install that is with error

**Comment by DonatoReis** [comment]
@shelld3v I will implement your tool in a script, but we have many errors to install.

I would also like you to test my script if possible.

**Comment by wellencamass** [comment]
hello, @shelld3v  is it possible to rewrite so go install be possible?
<img width="846" alt="изображение" src="https://user-images.githubusercontent.com/77920409/168592715-e0bbb5d4-14d7-4aab-9e9b-43b7ff3c6dfd.png">


P.S. now it works with GO111MODULE=off go get github.com/shelld3v/aquatone

**Comment by shelld3v** [comment]
Nice, I updated the README, closing as per
