### ISSUE TITLE
EMPTY aquatone_urls.txt

### ISSUE THREAD

**Issue by xavupkt** [shelld3v/aquatone#4]
The output file aquatone_urls.txt is empty.
Everything else looks fine.

**Comment by shelld3v** [comment]
Hi @xavupkt, I will check this soon, when I switch to my ubuntu system

**Comment by shelld3v** [comment]
@xavupkt I believe the root cause is that my aquatone disables `-save-body` by default. Enable it to can save URLs

**Comment by shelld3v** [comment]
I am closing this now! If you have any idea for a feature, tell me 😉
