### ISSUE TITLE
Error "Failed to create output directory ."

### ISSUE THREAD

**Issue by thezakman** [shelld3v/aquatone#6]
I tried to fix this with many ideas, but still cant make it work. Any idea?

**Comment by shelld3v** [comment]
Can you try running aquatone with `sudo` or creating a directory for aquatone output at `/tmp` and set output dir to it? (`-output /tmp/aquatone`)

**Comment by thezakman** [comment]
I solved, thanks. It was a error on my setup, my bad :)
