### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by cmprmsd** [shelld3v/aquatone#7]
Would this report work if one had no Internet?
I stumbled over this issue with the original project last week and this is because the project references external js.
It would be great to embed this into the project in order to be able to use it in restricted DMZs.

**Comment by shelld3v** [comment]
> Would this report work if one had no Internet?
> I stumbled over this issue with the original project last week and this is because the project references external js.
> It would be great to embed this into the project in order to be able to use it in restricted DMZs.

Yes, it will work without Internet in offline mode (`-offline` command-line flag)
