### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by luisfelipe3d** [shelld3v/aquatone#9]
Hi, first of all I would like to thank you for continuing to develop the project.

I would like to see an aquatone docker image like [Amass](https://github.com/OWASP/Amass) tool

**Comment by shelld3v** [comment]
To be honest I don't know how to create the Dockerfile=((

**Comment by wellenc-lex** [comment]
Dockerfile:

FROM golang:latest

RUN apt-get update && \
    apt-get install -yq chromium

#install aquatone binary
WORKDIR /opt/aquatone
RUN go get github.com/shelld3v/aquatone && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["aquatone"]

docker build -aquatone .

echo "domain.com" | docker run -v screenshots:/screenshots -v dockerresults:/dockerresults --rm -i aquatone -http-timeout 30000 -threads 5 -scan-timeout 10000 -screenshot-timeout 80000 -out /screenshots/1 -save-body false

**Comment by shelld3v** [comment]
Feel free to submit a pull request if you want
